### ISSUE TITLE
Character with single weapon (only equipped not slots) causes transfer to fail

### ISSUE THREAD

**Issue by netniV** [NigelHietala/ishtar-bugs#476] opened 2021-09-05 10:45 UTC
If you try and transfer a weapon from a character with only one item equipped and no secondary's to replace it with, the transfer fails when it should obtain a sutible item from the vault or another character.

**Comment by NigelBreslaw** [comment] 2021-09-05 10:48
Dupe of #437 which you raised 😂

**Closed as completed by NigelBreslaw** 2021-09-05 10:48 UTC
